# On every push this script is executed
on: push
name: Build and deploy GH Pages
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: bootstrap
        run: |
          git switch gh-pages
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          npm i
          mv node_modules static
          git add -f static/node_modules
          git commit -m "Install Bootstrap"
          git push
      - name: build_and_deploy
        uses: shalzz/zola-deploy-action@master
        env:
          # Target branch
          PAGES_BRANCH: gh-pages
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
